const WordArray = [
  "Aslam",
  "Taj Mahal",
  "Shiva",
  "Harry Potter",
  "Vladimir Putin",
  "Kebab",
  "Kangaroo",
  "Buddhism",
  "Napoleon",
  "Taylor Swift",
  "Pizzaria",
  "Shia Muslim",
  "Merkel",
  "Lamborgini",
  "Sushi",
  "Schindler's List",
  "Shin Chan",
  "Jeff Bezos",
  "Pewdiepie",
  "Margarita",
  "Stack Overflow",
  "Drugs",
  "Neymar",
  "Gordon Ramsay",
  "ISIS",
  "Budapest",
  "1818",
  "Bruce Springsteen",
  "Jacinda Arden",
  "Boris Johnson",
  "Led Zepplin",
  "Pink Floyd",
  "Maple Syrup",
  "The Godfather",
  "Chernobyl",
  "Lord of the Rings",
  "Stanley Kubrik",
  "Ingmar Bergman",
  "William Shakespear",
  "Isaac Newton",
  "Lebron James",
  "Tom and Jerry",
  "Doreamon",
  "Salman Khan",
  "Akshay Kumar",
  "Ramadan",
  "Schnitzel",
  "Kurwa",
  "The Hangover",
  "Money Heist",
  "Stranger Things",
  "Yellowstone National Park",
  "Pyramids",
  "Impractical Jokers",
  "Bengali Movie",
  "Assassins's Creed",
  "Cyberpunk 2077",
  "Uganda",
  "T-Series",
  "Hugh Jackman",
  "Quentin Tarantino",
  "Margot Robbie",
  "Kane Williamson",
  "Mark Calaway",
  "Usain Bolt",
  "Milkha Singh",
  "Satyajit Ray",
  "Apple Pie",
  "Pelmini",
  "Sauerbraten",
  "Chelow Kabab",
  "Bolognese",
  "Conor McGregor",
  "Harry Houdini",
  "Rasputin",
  "Barack Obama",
  "KPOP",
  "Santiago",
  "Communism",
  "Nelson Mandela",
  "Masai",
  "Ferdinand Marcos",
  "nasi lemak",
  "Bali",
  "Gaddaff",
  "Angkor Wat",
  "Genghis Khan",
  "Vodka",
  "Nokia",
  "Xiaomi",
  "Adidas",
  "Louis Vitton",
  "Monaco Grand Prix",
  "Notch",
  "Bjorn",
  "David Beckham",
  "Grenfell Tower",
  "Tosco",
  "Leicester City",
  "Chicago Bulls",
  "Bosch",
  "Everton",
  "Chocolate Cake",
  "Sangria",
  "Halong Bay",
  "Colosseum",
  "Scooby Doo",
  "Kuala Lumpur",
  "April The Giraffe",
  "Christopher Nolan",
  "Sergio Aguero",
  "CSGO",
  "Andy Murray",
  "Stonehenge",
  "Uluru",
  "Jennifer Aniston",
  "Aston Martin",
  "Hyundai",
  "Nissan",
  "IKEA",
  "Chanel",
  "Starbucks",
  "Porche",
  "Netflix",
  "Pepsi",
  "Cisco",
  "Budweiser",
  "KFC",
  "Tortillas",
  "Hanukkah",
  "Eminem",
  "Dallas Cowboys",
  "Power Rangers",
  "Life is Beautiful",
  "El laberinto del fauno",
  "Hideo Miyazaki",
  "Akira Kurosawa",
  "Burj Khalifa",
  "Machu Picchu",
  "Mont Saint-Michel",
  "St. Basil's Cathedral",
  "Neuschwanstein Castle",
  "Athens",
  "Victoria Falls",
  "Buckingham Palace",
  "Barcelona",
  "Ha Long Bay",
  "Guacamole",
  "Armani",
  "Emilia Clarke",
  "Vincent Van Gogh",
  "Bob Marley",
  "Aristotle",
  "Malala",
  "Tiger Wood",
  "Fiedel Castro",
  "Lee Kwan Yew",
  "Steve Irwin",
  "Bruce Lee",
  "Pele",
  "Cricket",
  "Shakira",
  "Rihanna",
  "Roald Amundsen",
  "Novak Djokovic",
  "Oscar Wilde",
  "Isaac Asimov",
  "Sheikh M. Rahman",
  "DIA DE LOS MUERTOS",
  "Songkran",
  "お盆",
  "PERAHERA FESTIVAL",
  "Quiver Tree",
  "Baobab Tree",
  "Salmon",
  "Tea",
  "Emu",
  "Kiwi",
  "Cow",
  "Fjord horse",
  "Lynx",
  "Bald Eagle",
  "Bulldog",
  "Osama Bin Laden",
  "Swiss franc",
  "Peso",
  "Mexican peso",
  "Rial",
  "Muhammad Ali",
  "Malcolm X",
  "Naruto",
  "Riga",
  "Bern",
  "Harare",
  "Beirut",
  "Cairo",
  "Prague",
  "Ottawa",
  "Jonty Rhodes",
  "Kim Kardasian",
  "Helsinki",
  "Paris",
  "Bishkek",
  "Valletta",
  "Bucharest",
  "Madrid",
  "Ankara",
  "Montevideo",
  "Muscat",
  "Quito",
  "Minsk",
  "Baby Shark",
  "Despacito",
  "Mary Kom",
  "Pablo Picasso",
  "Frida Kahlo",
  "Kendall Jenner",
  "Galileo Galilei",
  "Queen",
  "AC/DC",
  "Guns N'Roses",
  "Nirvana",
  "The Polide",
  "Arctic Monkeys",
  "Ernest Hemingway",
  "Agatha Christie",
  "Vivek Oberoi",
  "Vietnam War",
  "Kardinalschnitten",
  "Nanaimo Bar",
  "Apfelstrudel",
  "Kouign Amann",
  "Tarte Tatin",
  "Tiramisú",
  "Mr Bean",
  "Takeshi's Castle",
  "Jean-Luc Godard",
  "Federico Fellini",
  "Robert De Niro",
  "Bali",
  "Baidu",
  "Plitvice Lakes",
  "Cesky Krumlov",
  "Bicycle",
  "Auschwitz",
  "Slovak",
  "Russell Crowe",
  "Paul Pogba",
  "Diego Maradona",
  "Mohamed Salah",
  "Rami Malek",
  "Christoph Waltz",
  "Kangchenjunga",
  "Cho Oyu",
  "Thanksgiving",
  "The Departed",
  "Titanic",
  "Petra",
  "Rugby World Cup",
  "Michael Jackson",
  "Forrest Gump",
  "Churchill",
  "Skype",
  "Shooting",
  "Battersea Park",
  "flight 307",
  "Edmund Hillary",
  "Gastonbury Festival",
  "Roskilde Festival",
  "Rock al Parque",
  "Avatar",
  "Carlos Slim Helu",
  "Lakshmi Mittal",
  "Amancio Ortega",
  "Eike Batista",
  "Mont Blanc",
  "Batian",
  "Weisshorn",
  "King Louis",
  "Massacre of the Innocents",
  "Volta",
  "Sahara",
  "Alps",
  "Tarantula",
  "George Washington",
  "Юрий",
  "Niagra Falls",
  "Disneyland",
  "Россиянин",
  "German Shepard",
  "Juan",
  "Breaking Bad",
  "Mark Twain",
  "Juventus",
  "Mars",
  "Heineken",
  "Eid",
  "Koran",
];

module.exports = WordArray;
